In [5]:
import torch

张量(tensor)表示一个数值组成的数组, 数组可以有多个维度

In [6]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

使用'shape'属性访问张量的形状和元素
使用'numel()'访问元素总数

In [7]:
x.shape # []表示一个维度,12表示该维度有12个元素

torch.Size([12])

In [8]:
x.numel()

12

调用'reshape'改变张量形状而不改变元素数量和值

In [9]:
x = x.reshape(3, 4)     # 分割为3行4列(超出或者不够空位会报错)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0或1创建张量

In [10]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

使用'tensor'提供包含数值的python列表为张量中每个元素赋值

In [12]:
torch.tensor([[2, 1, 4,3], [1, 2, 3,4]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4]])

运算符视为按元素运算

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 3, 2, 3])
x + y, x - y, x * y, x / y, x**y, torch.exp(x)

(tensor([ 3.,  5.,  6., 11.]),
 tensor([-1., -1.,  2.,  5.]),
 tensor([ 2.,  6.,  8., 24.]),
 tensor([0.5000, 0.6667, 2.0000, 2.6667]),
 tensor([  1.,   8.,  16., 512.]),
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]))

使用'cat'将多个张量连结到一起

In [14]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))       # 指定数据类型为float32, reshape(3, 4)和reshape((3, 4))等效
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)              # dim表示在第几维合并(0行1列)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二维张量

In [15]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

使用`sum()`对所有元素求和

In [16]:
x.sum()

tensor(66.)

调用广播机制按行操作形状不同的元素

In [17]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [18]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])